// ════════════════════════════════════════════════════════════════════════════
//  receipt_view_screen.dart
//  Pranav Ladies Tailors — Professional Receipt View
// ════════════════════════════════════════════════════════════════════════════

import 'package:flutter/material.dart';

import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';
import 'package:pranav_tailors/core/theme/app_theme.dart';

// ── Item work-status ──────────────────────────────────────────────────────────

enum _ItemWorkStatus { complete, inProgress, unassigned }

// ── Dummy item model ──────────────────────────────────────────────────────────

class _ReceiptItem {
  const _ReceiptItem(
    this.name,
    this.price, {
    this.workStatus = _ItemWorkStatus.unassigned,
    this.assignedTo,
  });
  final String          name;
  final double          price;
  final _ItemWorkStatus workStatus;
  final String?         assignedTo; // only relevant for inProgress
}

// ── Dummy receipt data ────────────────────────────────────────────────────────

abstract class _Dummy {
  static const receiptNo    = 'PLT-2026-042';
  static const date         = '11 Jun 2026';
  static const customer     = 'Priya Sharma';
  static const phone        = '9876543210';
  static const address      = 'Shivaji Nagar, Pune - 411005';
  static const deliveryDate = '20 Jun 2026';
  static const isUrgent     = true;

  static const items = [
    _ReceiptItem('Silk Blouse × 2',  1800.0,
        workStatus: _ItemWorkStatus.complete),
    _ReceiptItem('Salwar Kameez',     2400.0,
        workStatus: _ItemWorkStatus.inProgress, assignedTo: 'Sunita'),
    _ReceiptItem('Lehenga Blouse',    1500.0,
        workStatus: _ItemWorkStatus.unassigned),
  ];

  static const designExtra  = 200.0;
  static const urgentCharge = 500.0;
  static const total        = 6400.0;
  static const advance      = 2500.0;
  static const remaining    = 3900.0;
}

// ── Bilingual labels ──────────────────────────────────────────────────────────

const _kEn = {
  'receipt_no':    'Receipt No.',
  'date':          'Date',
  'customer':      'Customer Name',
  'phone':         'Phone',
  'address':       'Address',
  'delivery':      'Delivery Date',
  'generated':     'Generated By',
  'sr':            'Sr.',
  'item':          'Item',
  'design':        'Design',
  'price':         'Price',
  'design_extra':  'Design Extra Charge',
  'urgent':        'Urgent Charge',
  'total':         'Total Amount',
  'advance':       'Advance Paid',
  'remaining':     'Remaining',
  'urgent_badge':  'URGENT ORDER',
  'terms_title':   'Terms & Conditions',
  'terms_1':       '1. Goods once delivered will not be exchanged.',
  'terms_2':       '2. Alterations are chargeable after 7 days.',
  'terms_3':       '3. Uncollected items after 30 days will be disposed.',
  'shop_tag':      'Ladies Dress & Blouse Specialist',
  'shop_sub':      'Pico • Fall • Beading Center',
};

const _kMr = {
  'receipt_no':    'पावती क्रमांक',
  'date':          'तारीख',
  'customer':      'ग्राहकाचे नाव',
  'phone':         'फोन',
  'address':       'पत्ता',
  'delivery':      'वितरण तारीख',
  'generated':     'तयार केले',
  'sr':            'क्र.',
  'item':          'वस्तू',
  'design':        'डिझाईन',
  'price':         'किंमत',
  'design_extra':  'डिझाईन अतिरिक्त शुल्क',
  'urgent':        'तातडी शुल्क',
  'total':         'एकूण रक्कम',
  'advance':       'आगाऊ रक्कम',
  'remaining':     'बाकी रक्कम',
  'urgent_badge':  'तातडी ऑर्डर',
  'terms_title':   'नियम व अटी',
  'terms_1':       '१. एकदा दिलेल्या वस्तू परत घेतल्या जाणार नाहीत.',
  'terms_2':       '२. ७ दिवसांनंतर दुरुस्तीवर शुल्क आकारले जाईल.',
  'terms_3':       '३. ३० दिवसांनंतर न घेतलेल्या वस्तू नष्ट केल्या जातील.',
  'shop_tag':      'लेडीज ड्रेस व ब्लाउज स्पेशलिस्ट',
  'shop_sub':      'पिको • फॉल • बीडिंग सेंटर',
};

// ════════════════════════════════════════════════════════════════════════════
//  Screen
// ════════════════════════════════════════════════════════════════════════════

class ReceiptViewScreen extends StatefulWidget {
  const ReceiptViewScreen({
    super.key,
    this.generatedBy = 'Manager',
    this.showActions = true,
  });

  /// The name of who created this receipt (e.g. "Manager", "Sunita", "Kaveri").
  final String generatedBy;

  /// When false, hides the language toggle and WhatsApp share button
  /// (used when opened from the Employee side).
  final bool showActions;

  @override
  State<ReceiptViewScreen> createState() => _ReceiptViewScreenState();
}

class _ReceiptViewScreenState extends State<ReceiptViewScreen> {
  bool _marathi = false;
  final _fmt = NumberFormat('#,##0.00');

  Map<String, String> get _L => _marathi ? _kMr : _kEn;
  String _l(String key) => _L[key] ?? key;

  // ── Share text ────────────────────────────────────────────────────────────
  String _buildShareText() {
    final sb = StringBuffer();
    sb.writeln('*Pranav Ladies Tailors*');
    sb.writeln('Shivaji Nagar, Pune | Ph: 9876500000');
    sb.writeln('─────────────────────');
    sb.writeln('${_l("receipt_no")}: ${_Dummy.receiptNo}');
    sb.writeln('${_l("date")}: ${_Dummy.date}');
    sb.writeln('${_l("customer")}: ${_Dummy.customer}');
    sb.writeln('${_l("phone")}: ${_Dummy.phone}');
    sb.writeln('${_l("delivery")}: ${_Dummy.deliveryDate}');
    sb.writeln('─────────────────────');
    for (int i = 0; i < _Dummy.items.length; i++) {
      sb.writeln('${i + 1}. ${_Dummy.items[i].name} — ₹${_fmt.format(_Dummy.items[i].price)}');
    }
    if (_Dummy.designExtra > 0) {
      sb.writeln('${_l("design_extra")}: ₹${_fmt.format(_Dummy.designExtra)}');
    }
    if (_Dummy.isUrgent) {
      sb.writeln('${_l("urgent")}: ₹${_fmt.format(_Dummy.urgentCharge)}');
    }
    sb.writeln('─────────────────────');
    sb.writeln('*${_l("total")}: ₹${_fmt.format(_Dummy.total)}*');
    sb.writeln('${_l("advance")}: ₹${_fmt.format(_Dummy.advance)}');
    sb.writeln('*${_l("remaining")}: ₹${_fmt.format(_Dummy.remaining)}*');
    sb.writeln('─────────────────────');
    sb.writeln('Thank you for your order! 🙏');
    return sb.toString();
  }

  Future<void> _shareWhatsApp() async {
    await Share.share(_buildShareText(), subject: 'Receipt ${_Dummy.receiptNo}');
  }

  // ─────────────────────────────────────────────────────────────────────────
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF5F5F5),
      appBar: _buildAppBar(),
      body: SingleChildScrollView(
        padding: const EdgeInsets.fromLTRB(16, 16, 16, 100),
        child: Container(
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(16),
            boxShadow: AppShadows.elevated,
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              _buildHeader(),
              _buildGoldDivider(),
              _buildCustomerSection(),
              _buildGoldDivider(thin: true),
              if (_Dummy.isUrgent) _buildUrgentBadge(),
              _buildItemsTable(),
              _buildGoldDivider(thin: true),
              _buildTotalsSection(),
              _buildGoldDivider(thin: true),
              _buildTermsFooter(),
            ],
          ),
        ),
      ),
      bottomNavigationBar: widget.showActions ? _buildBottomBar() : null,
    );
  }

  AppBar _buildAppBar() {
    return AppBar(
      backgroundColor: AppColors.primary,
      foregroundColor: Colors.white,
      elevation: 0,
      flexibleSpace: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            colors: [AppColors.topbarStart, AppColors.topbarEnd],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
        ),
      ),
      title: Text('Receipt View',
          style: TextStyle(fontFamily: 'Poppins', 
              fontSize: 18, fontWeight: FontWeight.w600, color: Colors.white)),
      actions: [
        IconButton(
          icon: const Icon(Icons.print_rounded, color: Colors.white),
          tooltip: 'Print',
          onPressed: () {},
        ),
        IconButton(
          icon: const Icon(Icons.download_rounded, color: Colors.white),
          tooltip: 'Save PDF',
          onPressed: () {},
        ),
      ],
    );
  }

  // ── Shop header ───────────────────────────────────────────────────────────
  Widget _buildHeader() {
    return Container(
      padding: const EdgeInsets.fromLTRB(20, 28, 20, 20),
      decoration: const BoxDecoration(
        gradient: LinearGradient(
          colors: [Color(0xFFFFF0F5), Colors.white],
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
        ),
        borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
      ),
      child: Column(
        children: [
          // Scissors icon
          Container(
            width: 60,
            height: 60,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              gradient: const LinearGradient(
                colors: [AppColors.topbarStart, AppColors.topbarEnd],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              boxShadow: AppShadows.card,
            ),
            child: const Icon(Icons.content_cut_rounded,
                color: Colors.white, size: 28),
          ),
          const SizedBox(height: 12),
          Text('Pranav Ladies Tailors',
              style: TextStyle(fontFamily: 'Poppins', 
                  fontSize: 20,
                  fontWeight: FontWeight.w800,
                  color: AppColors.primary,
                  letterSpacing: 0.3)),
          const SizedBox(height: 4),
          Text(_l('shop_tag'),
              style: TextStyle(fontFamily: 'Poppins', 
                  fontSize: 12, color: AppColors.textSecondary)),
          Text(_l('shop_sub'),
              style: TextStyle(fontFamily: 'Poppins', 
                  fontSize: 11, color: AppColors.textHint)),
          const SizedBox(height: 8),
          Text('Shivaji Nagar, Pune – 411005 | Ph: 9876500000',
              textAlign: TextAlign.center,
              style: TextStyle(fontFamily: 'Poppins', 
                  fontSize: 11, color: AppColors.textHint)),
          const SizedBox(height: 16),
          // Receipt number badge
          Container(
            padding:
                const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
            decoration: BoxDecoration(
              color: AppColors.primaryLight.withValues(alpha: 0.30),
              borderRadius: BorderRadius.circular(20),
              border:
                  Border.all(color: AppColors.primary.withValues(alpha: 0.30)),
            ),
            child: Text(
              '${_l("receipt_no")}: ${_Dummy.receiptNo}',
              style: TextStyle(fontFamily: 'Poppins', 
                  fontSize: 13,
                  fontWeight: FontWeight.w700,
                  color: AppColors.primary),
            ),
          ),
        ],
      ),
    );
  }

  // ── Gold divider ──────────────────────────────────────────────────────────
  Widget _buildGoldDivider({bool thin = false}) {
    return Container(
      height: thin ? 1 : 3,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: thin
              ? [
                  const Color(0xFFB8860B).withValues(alpha: 0.20),
                  const Color(0xFFB8860B).withValues(alpha: 0.60),
                  const Color(0xFFB8860B).withValues(alpha: 0.20),
                ]
              : [
                  const Color(0xFFB8860B).withValues(alpha: 0.40),
                  const Color(0xFFB8860B),
                  const Color(0xFFB8860B).withValues(alpha: 0.40),
                ],
        ),
      ),
    );
  }

  // ── Urgent badge ──────────────────────────────────────────────────────────
  Widget _buildUrgentBadge() {
    return Container(
      margin: const EdgeInsets.fromLTRB(16, 12, 16, 0),
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(
        color: AppColors.urgentLight,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: AppColors.urgent.withValues(alpha: 0.50)),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const Icon(Icons.bolt_rounded, color: AppColors.urgent, size: 18),
          const SizedBox(width: 6),
          Text(_l('urgent_badge'),
              style: TextStyle(fontFamily: 'Poppins', 
                  fontSize: 12,
                  fontWeight: FontWeight.w700,
                  color: AppColors.urgent,
                  letterSpacing: 1.2)),
        ],
      ),
    );
  }

  // ── Customer & receipt info ───────────────────────────────────────────────
  Widget _buildCustomerSection() {
    return Padding(
      padding: const EdgeInsets.fromLTRB(20, 16, 20, 16),
      child: Column(
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Left column
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _ReceiptField(label: _l('customer'), value: _Dummy.customer),
                    const SizedBox(height: 8),
                    _ReceiptField(label: _l('phone'),    value: _Dummy.phone),
                    const SizedBox(height: 8),
                    _ReceiptField(label: _l('address'),  value: _Dummy.address),
                  ],
                ),
              ),
              const SizedBox(width: 16),
              // Right column
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _ReceiptField(label: _l('date'),      value: _Dummy.date),
                    const SizedBox(height: 8),
                    _ReceiptField(label: _l('delivery'),  value: _Dummy.deliveryDate),
                    const SizedBox(height: 8),
                    _ReceiptField(label: _l('generated'), value: widget.generatedBy),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  // ── Items table ───────────────────────────────────────────────────────────
  Widget _buildItemsTable() {
    final headerStyle = TextStyle(fontFamily: 'Poppins', 
        fontSize: 11,
        fontWeight: FontWeight.w700,
        color: Colors.white);

    return Padding(
      padding: const EdgeInsets.fromLTRB(16, 16, 16, 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Table header
          Container(
            padding:
                const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            decoration: BoxDecoration(
              gradient: const LinearGradient(
                  colors: [AppColors.topbarStart, AppColors.topbarEnd]),
              borderRadius: BorderRadius.circular(8),
            ),
            child: Row(
              children: [
                SizedBox(
                    width: 28,
                    child: Text(_l('sr'), style: headerStyle)),
                Expanded(
                    flex: 3,
                    child: Text(_l('item'), style: headerStyle)),
                SizedBox(
                    width: 50,
                    child: Text(_l('design'),
                        style: headerStyle, textAlign: TextAlign.center)),
                SizedBox(
                    width: 80,
                    child: Text(_l('price'),
                        style: headerStyle, textAlign: TextAlign.right)),
              ],
            ),
          ),
          const SizedBox(height: 4),

          // Item rows
          ...List.generate(_Dummy.items.length, (i) {
            final item   = _Dummy.items[i];
            final isAlt  = i.isOdd;

            // Status badge config
            final Color  statusColor;
            final IconData statusIcon;
            final String statusLabel;
            switch (item.workStatus) {
              case _ItemWorkStatus.complete:
                statusColor  = AppColors.success;
                statusIcon   = Icons.check_circle_rounded;
                statusLabel  = '✓ Completed';
                break;
              case _ItemWorkStatus.inProgress:
                statusColor  = const Color(0xFF1565C0);
                statusIcon   = Icons.settings_rounded;
                statusLabel  = '⚙ In Progress';
                break;
              case _ItemWorkStatus.unassigned:
                statusColor  = AppColors.urgent;
                statusIcon   = Icons.bolt_rounded;
                statusLabel  = '⚡ Unassigned';
                break;
            }

            return Container(
              decoration: BoxDecoration(
                color: isAlt
                    ? AppColors.surface2.withValues(alpha: 0.50)
                    : Colors.white,
                border: const Border(
                    bottom: BorderSide(color: AppColors.border, width: 0.5)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Main item row
                  Padding(
                    padding: const EdgeInsets.fromLTRB(12, 10, 12, 4),
                    child: Row(
                      children: [
                        SizedBox(
                          width: 28,
                          child: Text('${i + 1}.',
                              style: TextStyle(fontFamily: 'Poppins',
                                  fontSize: 12,
                                  color: AppColors.textHint)),
                        ),
                        Expanded(
                          flex: 3,
                          child: Text(item.name,
                              style: TextStyle(fontFamily: 'Poppins',
                                  fontSize: 13,
                                  fontWeight: FontWeight.w500,
                                  color: AppColors.textPrimary)),
                        ),
                        SizedBox(
                          width: 50,
                          child: Center(
                            child: Container(
                              width: 40,
                              height: 40,
                              decoration: BoxDecoration(
                                color: AppColors.surface2,
                                borderRadius: BorderRadius.circular(8),
                                border: Border.all(color: AppColors.border),
                              ),
                              child: const Icon(Icons.image_rounded,
                                  size: 20, color: AppColors.textHint),
                            ),
                          ),
                        ),
                        SizedBox(
                          width: 80,
                          child: Text('₹${_fmt.format(item.price)}',
                              textAlign: TextAlign.right,
                              style: TextStyle(fontFamily: 'Poppins',
                                  fontSize: 13,
                                  fontWeight: FontWeight.w600,
                                  color: AppColors.textPrimary)),
                        ),
                      ],
                    ),
                  ),

                  // Status badge row
                  Padding(
                    padding: const EdgeInsets.fromLTRB(40, 0, 12, 8),
                    child: Row(
                      children: [
                        // Status pill
                        Container(
                          padding: const EdgeInsets.symmetric(
                              horizontal: 8, vertical: 3),
                          decoration: BoxDecoration(
                            color: statusColor.withValues(alpha: 0.10),
                            borderRadius: BorderRadius.circular(20),
                            border: Border.all(
                                color: statusColor.withValues(alpha: 0.40)),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Icon(statusIcon,
                                  size: 11, color: statusColor),
                              const SizedBox(width: 4),
                              Text(statusLabel,
                                  style: TextStyle(
                                      fontFamily: 'Poppins',
                                      fontSize: 10.5,
                                      fontWeight: FontWeight.w700,
                                      color: statusColor)),
                            ],
                          ),
                        ),
                        // In-progress: show worker name
                        if (item.workStatus == _ItemWorkStatus.inProgress &&
                            item.assignedTo != null) ...[
                          const SizedBox(width: 6),
                          Icon(Icons.person_rounded,
                              size: 12,
                              color: AppColors.textHint),
                          const SizedBox(width: 3),
                          Text('Working: ${item.assignedTo}',
                              style: const TextStyle(
                                  fontFamily: 'Poppins',
                                  fontSize: 10.5,
                                  color: AppColors.textSecondary)),
                        ],
                        // Unassigned: show assign button
                        if (item.workStatus == _ItemWorkStatus.unassigned) ...[
                          const SizedBox(width: 8),
                          GestureDetector(
                            onTap: () =>
                                context.push('/manager/work-queue'),
                            child: Container(
                              padding: const EdgeInsets.symmetric(
                                  horizontal: 8, vertical: 3),
                              decoration: BoxDecoration(
                                color: AppColors.primary
                                    .withValues(alpha: 0.10),
                                borderRadius: BorderRadius.circular(20),
                                border: Border.all(
                                    color: AppColors.primary
                                        .withValues(alpha: 0.40)),
                              ),
                              child: const Row(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  Icon(Icons.assignment_ind_rounded,
                                      size: 11, color: AppColors.primary),
                                  SizedBox(width: 4),
                                  Text('Assign in Work Queue',
                                      style: TextStyle(
                                          fontFamily: 'Poppins',
                                          fontSize: 10,
                                          fontWeight: FontWeight.w600,
                                          color: AppColors.primary)),
                                ],
                              ),
                            ),
                          ),
                        ],
                      ],
                    ),
                  ),
                ],
              ),
            );
          }),

          // Extra rows
          if (_Dummy.designExtra > 0)
            _ExtraRow(
              label: _l('design_extra'),
              value: '₹${_fmt.format(_Dummy.designExtra)}',
              color: const Color(0xFF5E35B1),
            ),
          if (_Dummy.isUrgent)
            _ExtraRow(
              label: _l('urgent'),
              value: '₹${_fmt.format(_Dummy.urgentCharge)}',
              color: AppColors.urgent,
              icon: Icons.bolt_rounded,
            ),
        ],
      ),
    );
  }

  // ── Totals section ────────────────────────────────────────────────────────
  Widget _buildTotalsSection() {
    return Container(
      margin: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        gradient: const LinearGradient(
          colors: [Color(0xFFFFF0F5), Color(0xFFFFF8FA)],
        ),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: AppColors.primary.withValues(alpha: 0.25)),
      ),
      child: Column(
        children: [
          // Total row
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
            decoration: BoxDecoration(
              gradient: const LinearGradient(
                  colors: [AppColors.topbarStart, AppColors.topbarEnd]),
              borderRadius: const BorderRadius.vertical(top: Radius.circular(12)),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(_l('total'),
                    style: TextStyle(fontFamily: 'Poppins', 
                        fontSize: 15,
                        fontWeight: FontWeight.w700,
                        color: Colors.white)),
                Text('₹${_fmt.format(_Dummy.total)}',
                    style: TextStyle(fontFamily: 'Poppins', 
                        fontSize: 18,
                        fontWeight: FontWeight.w800,
                        color: Colors.white)),
              ],
            ),
          ),
          Padding(
            padding:
                const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            child: Column(
              children: [
                _TotalRow(
                    label: _l('advance'),
                    value: '₹${_fmt.format(_Dummy.advance)}',
                    color: AppColors.success),
                const Divider(color: AppColors.border, height: 14),
                _TotalRow(
                    label: _l('remaining'),
                    value: '₹${_fmt.format(_Dummy.remaining)}',
                    color: AppColors.primary,
                    isBold: true,
                    fontSize: 16),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // ── Terms footer ──────────────────────────────────────────────────────────
  Widget _buildTermsFooter() {
    return Container(
      padding: const EdgeInsets.fromLTRB(20, 16, 20, 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.gavel_rounded, size: 14, color: AppColors.textHint),
              const SizedBox(width: 6),
              Text(_l('terms_title'),
                  style: TextStyle(fontFamily: 'Poppins', 
                      fontSize: 12,
                      fontWeight: FontWeight.w700,
                      color: AppColors.textSecondary)),
            ],
          ),
          const SizedBox(height: 6),
          _TermLine(_l('terms_1')),
          _TermLine(_l('terms_2')),
          _TermLine(_l('terms_3')),
          const SizedBox(height: 14),
          Center(
            child: Text('Thank You for Your Business 🙏',
                style: TextStyle(fontFamily: 'Poppins', 
                    fontSize: 12,
                    fontWeight: FontWeight.w600,
                    color: AppColors.primary)),
          ),
        ],
      ),
    );
  }

  // ── Bottom bar: language toggle + WhatsApp share ──────────────────────────
  Widget _buildBottomBar() {
    return Container(
      padding: EdgeInsets.fromLTRB(
          16, 12, 16, 12 + MediaQuery.of(context).padding.bottom),
      decoration: BoxDecoration(
        color: AppColors.surface,
        border: const Border(top: BorderSide(color: AppColors.border)),
        boxShadow: AppShadows.elevated,
      ),
      child: Row(
        children: [
          // Language toggle
          GestureDetector(
            onTap: () => setState(() => _marathi = !_marathi),
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
              decoration: BoxDecoration(
                color: _marathi
                    ? AppColors.primaryLight.withValues(alpha: 0.30)
                    : AppColors.surface2,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(
                    color: _marathi ? AppColors.primary : AppColors.border),
              ),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text(
                    _marathi ? 'EN' : 'मर',
                    style: TextStyle(fontFamily: 'Poppins', 
                        fontSize: 14,
                        fontWeight: FontWeight.w800,
                        color: _marathi ? AppColors.primary : AppColors.textSecondary),
                  ),
                  Text(
                    _marathi ? 'English' : 'मराठी',
                    style: TextStyle(fontFamily: 'Poppins', 
                        fontSize: 9,
                        color: _marathi
                            ? AppColors.primary
                            : AppColors.textHint),
                  ),
                ],
              ),
            ),
          ),
          const SizedBox(width: 12),
          // WhatsApp share button
          Expanded(
            child: DecoratedBox(
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [Color(0xFFB8860B), Color(0xFFDAA520)],
                ),
                borderRadius: BorderRadius.circular(12),
                boxShadow: AppShadows.card,
              ),
              child: ElevatedButton.icon(
                onPressed: _shareWhatsApp,
                icon: const Icon(Icons.share_rounded,
                    color: Colors.white, size: 18),
                label: Text('Share via WhatsApp',
                    style: TextStyle(fontFamily: 'Poppins', 
                        fontWeight: FontWeight.w700,
                        color: Colors.white,
                        fontSize: 14)),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.transparent,
                  shadowColor: Colors.transparent,
                  padding: const EdgeInsets.symmetric(vertical: 14),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12)),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ════════════════════════════════════════════════════════════════════════════
//  Small helper widgets
// ════════════════════════════════════════════════════════════════════════════

class _ReceiptField extends StatelessWidget {
  const _ReceiptField({required this.label, required this.value});
  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label,
            style: TextStyle(fontFamily: 'Poppins', 
                fontSize: 10.5,
                fontWeight: FontWeight.w500,
                color: AppColors.textHint)),
        Text(value,
            style: TextStyle(fontFamily: 'Poppins', 
                fontSize: 13,
                fontWeight: FontWeight.w600,
                color: AppColors.textPrimary)),
      ],
    );
  }
}

class _ExtraRow extends StatelessWidget {
  const _ExtraRow({
    required this.label,
    required this.value,
    required this.color,
    this.icon,
  });
  final String label;
  final String value;
  final Color color;
  final IconData? icon;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.06),
        border: const Border(
            bottom: BorderSide(color: AppColors.border, width: 0.5)),
      ),
      child: Row(
        children: [
          if (icon != null) ...[
            Icon(icon, size: 14, color: color),
            const SizedBox(width: 6),
          ] else ...[
            const SizedBox(width: 20),
          ],
          Expanded(
            child: Text(label,
                style: TextStyle(fontFamily: 'Poppins', 
                    fontSize: 12.5,
                    fontWeight: FontWeight.w500,
                    color: color)),
          ),
          Text(value,
              style: TextStyle(fontFamily: 'Poppins', 
                  fontSize: 13, fontWeight: FontWeight.w600, color: color)),
        ],
      ),
    );
  }
}

class _TotalRow extends StatelessWidget {
  const _TotalRow({
    required this.label,
    required this.value,
    required this.color,
    this.isBold = false,
    this.fontSize = 13,
  });
  final String label;
  final String value;
  final Color color;
  final bool isBold;
  final double fontSize;

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(label,
            style: TextStyle(fontFamily: 'Poppins', 
                fontSize: fontSize,
                fontWeight: isBold ? FontWeight.w700 : FontWeight.w500,
                color: AppColors.textPrimary)),
        Text(value,
            style: TextStyle(fontFamily: 'Poppins', 
                fontSize: isBold ? fontSize + 1 : fontSize,
                fontWeight: isBold ? FontWeight.w800 : FontWeight.w600,
                color: color)),
      ],
    );
  }
}

class _TermLine extends StatelessWidget {
  const _TermLine(this.text);
  final String text;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(top: 3),
      child: Text(text,
          style: TextStyle(fontFamily: 'Poppins', 
              fontSize: 10.5, color: AppColors.textHint, height: 1.4)),
    );
  }
}
