"""initial_schema

Revision ID: 158d8797497a
Revises: 
Create Date: 2026-06-19 02:46:35.438112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158d8797497a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('stitch_bill', 'employee_payment', name='expensetype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_date', 'expenses', ['date'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index('ix_expenses_type', 'expenses', ['type'], unique=False)
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('partial_complete', 'order_complete', 'overdue_apology', 'tomorrow_reminder', name='messagetype'), nullable=False),
    sa.Column('language', sa.Enum('english', 'marathi', name='messagelanguage'), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'language', name='uq_message_template_type_language')
    )
    op.create_index(op.f('ix_message_templates_id'), 'message_templates', ['id'], unique=False)
    op.create_index('ix_message_templates_language', 'message_templates', ['language'], unique=False)
    op.create_index('ix_message_templates_type', 'message_templates', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('role', sa.Enum('manager', 'employee', name='userrole'), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('fcm_token', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_customers_created_by', 'customers', ['created_by'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index('ix_customers_name', 'customers', ['name'], unique=False)
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    op.create_table('design_gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('blouse', 'dress', name='gallerytype'), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_design_gallery_created_at', 'design_gallery', ['created_at'], unique=False)
    op.create_index(op.f('ix_design_gallery_id'), 'design_gallery', ['id'], unique=False)
    op.create_index('ix_design_gallery_type', 'design_gallery', ['type'], unique=False)
    op.create_index('ix_design_gallery_uploaded_by', 'design_gallery', ['uploaded_by'], unique=False)
    op.create_table('employee_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('given_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['given_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employee_payments_date', 'employee_payments', ['date'], unique=False)
    op.create_index('ix_employee_payments_employee_id', 'employee_payments', ['employee_id'], unique=False)
    op.create_index('ix_employee_payments_given_by', 'employee_payments', ['given_by'], unique=False)
    op.create_index(op.f('ix_employee_payments_id'), 'employee_payments', ['id'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notices_created_at', 'notices', ['created_at'], unique=False)
    op.create_index('ix_notices_created_by', 'notices', ['created_by'], unique=False)
    op.create_index(op.f('ix_notices_id'), 'notices', ['id'], unique=False)
    op.create_index('ix_notices_is_active', 'notices', ['is_active'], unique=False)
    op.create_table('blouse_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('back_length', sa.Float(), nullable=True),
    sa.Column('full_shoulder', sa.Float(), nullable=True),
    sa.Column('shoulder_strap', sa.Float(), nullable=True),
    sa.Column('back_neck_depth', sa.Float(), nullable=True),
    sa.Column('front_neck_depth', sa.Float(), nullable=True),
    sa.Column('shoulder_to_apex', sa.Float(), nullable=True),
    sa.Column('front_length', sa.Float(), nullable=True),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('sleeve_length', sa.Float(), nullable=True),
    sa.Column('arm_round', sa.Float(), nullable=True),
    sa.Column('sleeve_round', sa.Float(), nullable=True),
    sa.Column('arm_hole', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_index('ix_blouse_measurements_customer_id', 'blouse_measurements', ['customer_id'], unique=False)
    op.create_index(op.f('ix_blouse_measurements_id'), 'blouse_measurements', ['id'], unique=False)
    op.create_table('dress_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('upper_back_length', sa.Float(), nullable=True),
    sa.Column('upper_full_shoulder', sa.Float(), nullable=True),
    sa.Column('upper_shoulder_strap', sa.Float(), nullable=True),
    sa.Column('upper_back_neck_depth', sa.Float(), nullable=True),
    sa.Column('upper_front_neck_depth', sa.Float(), nullable=True),
    sa.Column('upper_shoulder_to_apex', sa.Float(), nullable=True),
    sa.Column('upper_front_length', sa.Float(), nullable=True),
    sa.Column('upper_chest', sa.Float(), nullable=True),
    sa.Column('upper_waist', sa.Float(), nullable=True),
    sa.Column('upper_sleeve_length', sa.Float(), nullable=True),
    sa.Column('upper_arm_round', sa.Float(), nullable=True),
    sa.Column('upper_sleeve_round', sa.Float(), nullable=True),
    sa.Column('upper_arm_hole', sa.Float(), nullable=True),
    sa.Column('upper_seat', sa.Float(), nullable=True),
    sa.Column('lower_height', sa.Float(), nullable=True),
    sa.Column('lower_waist', sa.Float(), nullable=True),
    sa.Column('lower_seat', sa.Float(), nullable=True),
    sa.Column('lower_bottom', sa.Float(), nullable=True),
    sa.Column('dupatta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_index('ix_dress_measurements_customer_id', 'dress_measurements', ['customer_id'], unique=False)
    op.create_index(op.f('ix_dress_measurements_id'), 'dress_measurements', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_no', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('design_extra_charge', sa.Float(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('urgent_cost', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('advance_paid', sa.Float(), nullable=False),
    sa.Column('remaining', sa.Float(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'complete', 'delivered', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_customer_id', 'orders', ['customer_id'], unique=False)
    op.create_index('ix_orders_delivery_date', 'orders', ['delivery_date'], unique=False)
    op.create_index('ix_orders_generated_by', 'orders', ['generated_by'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_receipt_no'), 'orders', ['receipt_no'], unique=True)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('design_image_url', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('unassigned', 'in_progress', 'complete', name='orderitemstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_items_assigned_to', 'order_items', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_status', 'order_items', ['status'], unique=False)
    op.create_table('order_sample_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_sample_images_id'), 'order_sample_images', ['id'], unique=False)
    op.create_index('ix_order_sample_images_order_id', 'order_sample_images', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_sample_images_order_id', table_name='order_sample_images')
    op.drop_index(op.f('ix_order_sample_images_id'), table_name='order_sample_images')
    op.drop_table('order_sample_images')
    op.drop_index('ix_order_items_status', table_name='order_items')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_index('ix_order_items_assigned_to', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index(op.f('ix_orders_receipt_no'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index('ix_orders_generated_by', table_name='orders')
    op.drop_index('ix_orders_delivery_date', table_name='orders')
    op.drop_index('ix_orders_customer_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_dress_measurements_id'), table_name='dress_measurements')
    op.drop_index('ix_dress_measurements_customer_id', table_name='dress_measurements')
    op.drop_table('dress_measurements')
    op.drop_index(op.f('ix_blouse_measurements_id'), table_name='blouse_measurements')
    op.drop_index('ix_blouse_measurements_customer_id', table_name='blouse_measurements')
    op.drop_table('blouse_measurements')
    op.drop_index('ix_notices_is_active', table_name='notices')
    op.drop_index(op.f('ix_notices_id'), table_name='notices')
    op.drop_index('ix_notices_created_by', table_name='notices')
    op.drop_index('ix_notices_created_at', table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_employee_payments_id'), table_name='employee_payments')
    op.drop_index('ix_employee_payments_given_by', table_name='employee_payments')
    op.drop_index('ix_employee_payments_employee_id', table_name='employee_payments')
    op.drop_index('ix_employee_payments_date', table_name='employee_payments')
    op.drop_table('employee_payments')
    op.drop_index('ix_design_gallery_uploaded_by', table_name='design_gallery')
    op.drop_index('ix_design_gallery_type', table_name='design_gallery')
    op.drop_index(op.f('ix_design_gallery_id'), table_name='design_gallery')
    op.drop_index('ix_design_gallery_created_at', table_name='design_gallery')
    op.drop_table('design_gallery')
    op.drop_index('ix_customers_phone', table_name='customers')
    op.drop_index('ix_customers_name', table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index('ix_customers_created_by', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_message_templates_type', table_name='message_templates')
    op.drop_index('ix_message_templates_language', table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_id'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index('ix_expenses_type', table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index('ix_expenses_date', table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
